# <center> Adult Dataset-ML Part </center>

### INDEX
<ul>
 <li><a href="#ML">Machine Learning </a></li>
</ul>

<a id="ML"> </a>
## Machine Learning

In [1]:
# importing needed libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn import preprocessing
from sklearn.metrics import accuracy_score,
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier 
from sklearn.metrics import confusion_matrix 
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

In [2]:
df=pd.read_csv('../data/processed/Adult_Salries_processed.csv')
df

,age,fnlwgt,educational-num,capital-gain,capital-loss,hours-per-week,workclass_Local-gov,workclass_Private,workclass_Self-emp-inc,workclass_Self-emp-not-inc,...,relationship_Other-relative,relationship_Own-child,relationship_Unmarried,relationship_Wife,race_Asian-Pac-Islander,race_Black,race_Other,race_White,gender_Male,income_>50K
0,25,226802,7,0,0,40,0,1,0,0,...,0,1,0,0,0,1,0,0,1,0
1,38,89814,9,0,0,50,0,1,0,0,...,0,0,0,0,0,0,0,1,1,0
2,28,336951,12,0,0,40,1,0,0,0,...,0,0,0,0,0,0,0,1,1,1
3,44,160323,10,7688,0,40,0,1,0,0,...,0,0,0,0,0,1,0,0,1,1
4,34,198693,6,0,0,30,0,1,0,0,...,0,0,0,0,0,0,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45170,27,257302,12,0,0,38,0,1,0,0,...,0,0,0,1,0,0,0,1,0,0
45171,40,154374,9,0,0,40,0,1,0,0,...,0,0,0,0,0,0,0,1,1,1
45172,58,151910,9,0,0,40,0,1,0,0,...,0,0,1,0,0,0,0,1,0,0
45173,22,201490,9,0,0,20,0,1,0,0,...,0,1,0,0,0,0,0,1,1,0
45174,52,287927,9,15024,0,40,0,0,1,0,...,0,0,0,1,0,0,0,1,0,1

In [3]:
x=df.drop('income_>50K',axis=1)
y=df['income_>50K']

In [4]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [5]:
scaler=StandardScaler()

In [6]:
x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)

In [7]:
models={
    'lr':LogisticRegression(),
    'KNN':KNeighborsClassifier(n_neighbors=3),
    'NB':GaussianNB(),
    'dt':DecisionTreeClassifier(),
    'RF':RandomForestClassifier(n_estimators=13),
    'xgb':XGBClassifier(n_estimators=10)
}

In [8]:
for name,model in models.items():
    print(name)
    model.fit(x_train,y_train)
    y_pred=model.predict(x_train)
    print('train_conf',confusion_matrix(y_train,y_pred))
    print('train_conf',confusion_matrix(y_test,model.predict(x_test)))
    print('acc_train',accuracy_score(y_train,y_pred))
    print('acc_test',accuracy_score(y_test,model.predict(x_test)))
    print('-'*30)

lr
train_conf [[25275  1945]
 [ 3564  5356]]
train_conf [[6323  430]
 [ 920 1362]]

NameError: name 'accuracy_score' is not defined

 ### i will choose go with boost

In [ ]:
model=XGBClassifier(n_estimators=10)
model.fit(x_train,y_train)

In [ ]:
import joblib
joblib.dump(scaler,'scaler.h5')
joblib.dump(model,'model.h5')

In [ ]:
df.info()

In [ ]:
df.iloc[2]